import fs from 'fs/promises';
import path from 'path';

const filePath = path.resolve('src/integrations/supabase/client.ts');

const content = `// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY as string;

// Import the supabase client like this:
// import { supabase } from '@/integrations/supabase/client';

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
`;

await fs.writeFile(filePath, content, 'utf8');
console.log('Supabase client generated at', filePath);

